allowBuilds:
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - '@fumadocs/base-ui@16.15.9'
  - fumadocs-core@16.15.9
  - fumadocs-openapi@11.4.2
overrides:
  '@types/react': 19.3.0
  '@types/react-dom': 19.3.0
